### ISSUE TITLE
BUG: Failed to execute 'insertBefore' on 'Node' i button element på datasets page

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-portal#1654]
### Nåværende oppførsel

`application: "fdk-portal"
image: "4b6c2f717f47a3a7b716f05a83226c5352873e79"
location: "https://data.norge.no/datasets?orgPath=%2FSTAT%2F983887457%2F889640782&provenance=NASJONAL&spatial=Norge&losTheme=arbeid%2Farbeidsliv"
message: "Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."
name: "NotFoundError"
namespace: "prod"
trace: "
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at button
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at s (https://data.norge.no/8566.1c235927238ecbfd62a7.js:1:2488)
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at div
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at p (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:711991)
    at article
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at x (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:642486)
    at w (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:350312)
    at _e (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:31160)
    at div
    at w (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:630688)
    at ErrorBoundary (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:864674)
    at section
    at div
    at I (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:33082)
    at main
    at O (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:1283629)
    at e (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:25001)
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at t
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:22441)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:24458)
    at div
    at div
    at w (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:1297472)
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at ErrorBoundary (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:864674)
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at t (https://data.norge.no/3702.9b673bb195ad1df8f1d4.js:2:21997)
    at s (https://data.norge.no/3702.9b673bb195ad1df8f1d4.js:2:32499)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:22441)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:24458)
    at div
    at z (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:136629)
    at ErrorBoundary (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:864674)
    at f (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:8004)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:22441)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:18849)
    at n (https://data.norge.no/4655.4b742fafe4738cfd7251.js:2:25558)
    at Z (https://data.norge.no/6706.08cb4e6f17ffec34a9e8.js:2:10149)
    at Ii (https://data.norge.no/9597.b888bb0ec745ab9325a3.js:1:136190)
    at f (https://data.norge.no/638.70fc09cba99566996dab.js:2:15424)
    at v (https://data.norge.no/6030.ea8c46b52dbba58d3a92.js:2:1327311)
    at _e (https://data.norge.no/8117.40e1c1d31d95784a0f3f.js:2:31160)
    at K (https://data.norge.no/752.f4467df688dfa7c17d0a.js:1:9563)"`

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
https://github.com/facebook/react/issues/11538
